### ISSUE TITLE
Fails to replace some special characters

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-safe-class-names#31]
This is mostly an issue with the regex we do for PostCSS, which affects replacements in the `<style>` tag.

For example, this will fail:

```css
.w-\[600px\] {
  width: 600px;
}
```
